adding_github_actions_configurations

diff --git a/.github/workflows/github-actions.yaml b/.github/workflows/github-actions.yaml
--- a/.github/workflows/github-actions.yaml
+++ b/.github/workflows/github-actions.yaml
@@ -1,31 +1,35 @@
 name: Test and Deploy
 on: [push]
-jobs:
- build:
-   runs-on: ubuntu-latest
-   steps:
-     - name: Trigger Test Suite
-       run: |
-         response=$(curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_PASSWORD }} -X POST https://lcnc-api.browserstack.com/api/v1/test-suite/${{ secrets.TEST_SUITE_ID }}/run)       
-         BUILD_ID=$(echo $response | jq -r '.build_id')
-         echo "Build ID: $BUILD_ID"
 
-     - name: Check Build Status
-       run: |
-         buildStatus=""
-         retryInterval=30
-         while [[ ("$buildStatus" != "passed" && "$buildStatus" != "failed") ]]; do
-           response=$(curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_PASSWORD }} -s https://lcnc-api.browserstack.com/api/v1/builds/${BUILD_ID}/status)
-           buildStatus=$(echo $response | jq -r '.build_status')
-           sleep $retryInterval
-         done
-         if [[ "$buildStatus" == "passed" ]]; then
-           echo "Build passed"
-           # Add further steps for actions to be taken if build passed
-         elif [[ "$buildStatus" == "failed" ]]; then
-           echo "Build failed"
-           exit 1
-         else
-           echo "Build status unstable"
-           exit 1
-         fi
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Trigger Test Suite
+        id: trigger_test_suite
+        run: |
+          response=$(curl -u akashdubey2:S51t45b15qvwFVjpnSDs -X POST https://lcnc-api.browserstack.com/api/v1/test-suite/${{bde1c4764583bb67b4550a7d85bf4510e9cc33fe}}/run)
+          BUILD_ID=$(echo $response | jq -r '.build_id')
+          echo "::set-output name=build_id::$BUILD_ID"
+          echo "Build ID: $BUILD_ID"
+          
+      - name: Check Build Status
+        run: |
+          buildStatus=""
+          retryInterval=30
+          BUILD_ID=${{ steps.trigger_test_suite.outputs.build_id }}
+          while [[ ("$buildStatus" != "passed" && "$buildStatus" != "failed") ]]; do
+            response=$(curl -u akashdubey2:S51t45b15qvwFVjpnSDs -s https://lcnc-api.browserstack.com/api/v1/builds/$BUILD_ID/status)
+            buildStatus=$(echo $response | jq -r '.build_status')
+            sleep $retryInterval
+          done
+          if [[ "$buildStatus" == "passed" ]]; then
+            echo "Build passed"
+            # Add further steps for actions to be taken if build passed
+          elif [[ "$buildStatus" == "failed" ]]; then
+            echo "Build failed"
+            exit 1
+          else
+            echo "Build status unstable"
+            exit 1
+          fi
